// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGZVUjHWHj-jXruT0mGyCYSv3bJPviZGk',
    appId: '1:1071342117353:web:77618fa74c11a0d9d5ab78',
    messagingSenderId: '1071342117353',
    projectId: 'math-to-cash',
    authDomain: 'math-to-cash.firebaseapp.com',
    storageBucket: 'math-to-cash.appspot.com',
    measurementId: 'G-FHH0CMHR1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9xuLk8kdKrcfv8IC_CgDiV8FKevXRDV8',
    appId: '1:1071342117353:android:a359f92e023bd280d5ab78',
    messagingSenderId: '1071342117353',
    projectId: 'math-to-cash',
    storageBucket: 'math-to-cash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdUnd61BOk6hXO4hX2RqQmjrJLK3TVsa4',
    appId: '1:1071342117353:ios:a43a0fb23d7684d5d5ab78',
    messagingSenderId: '1071342117353',
    projectId: 'math-to-cash',
    storageBucket: 'math-to-cash.appspot.com',
    iosClientId: '1071342117353-p8fo2m20csk66dnkan0f8akg5uo8b968.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathToCash',
  );
}
